version: '2'
services:
  nodes2020-app:
    image: nodes2020
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - ORG_NEO4J_DRIVER_URI=bolt://nodes2020-neo4j:7687
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  nodes2020-neo4j:
    extends:
      file: neo4j.yml
      service: nodes2020-neo4j
